name: Test
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"
jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, "windows-latest"]
        node-version: [12.x, 13.x, 14.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
      - run: npm i
      - run: npm run build
      - run: npm run test